name: Billiards
options:
  bundleIdPrefix: com.game
targets:
  Billiards:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
    resources:
      - path: GameWeb
    settings:
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIRequiresFullScreen: YES
      INFOPLIST_KEY_UIStatusBarHidden: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGN_IDENTITY: ""
      VALIDATE_PRODUCT: NO # <-- BẠN THÊM DÒNG NÀY VÀO ĐÂY
